version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[palette]
primary_background = "#747674"
primary_text = "#E9F9E9"

[[blocks]]
  type = "prompt"
  alignment = "left"
  
  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:primary_text"
    background = "p:primary_background"
    template = " {{.Path}} "

    [blocks.segments.properties]
    style = "mixed"
    max_depth = 5

  [[blocks.segments]]
    type = "git"
    style = "plain"
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<red>*</>{{ end }}{{ if gt .Behind 0 }}<cyan>⇣</>{{ end }}{{ if gt .Ahead 0 }}<green>⇡</>{{ end }} '
    background = "p:primary_background"
    foreground = "p:primary_text"
    display_status = true
    Text = ""
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
    fetch_status = true
    fetch_upstream_icon = true
    source = "cli"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:primary_background"
    background = "transparent"
    template = ""

